<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\wisski_triplify\TriplifyManager;

function wisski_triplify_wisski_individual_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
#dpm("begin triplify", "aa");
#  $success = (new TriplifyManager())->triplify($entity);
#dpm($success);
#  $success = (new TriplifyManager())->triplify($entity);
  
}

/**
 * Implementation of Hook_help
 */
function wisski_triplify_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.wisski_triplify':
      return '<p>' . t('This module generates triples from text entries for the WissKI infrastructure.') . '</p>';
  }
}


function wisski_triplify_wisski_individual_update(EntityInterface $entity) {
  $success = (new TriplifyManager())->triplify($entity);
}

function wisski_triplify_wisski_individual_insert(EntityInterface $entity) {
  $success = (new TriplifyManager())->triplify($entity);
}


