<?php

use Drupal\Core\Routing\RouteMatchInterface;
// $ID$
/**
* Basic module for the WissKI-Communication with Drupal 7
* Provides the Pathbuilder Interface
* Handles Basic mappings
*
*
* @author: Mark Fichtner, Martin Scholz
* 
*/
function wisski_wave_help($route_name, RouteMatchInterface $route_match) {
   switch ($route_name) {
     case 'help.page.wisski_wave':
       return '<p>' . t('Basic module for the WissKI-Communication with Drupal 7. Provides the Pathbuilder Interface. Handles Basic mappings.') . '</p>';
   }
}
