# Schema for configuration of the pathbuilder module

wisski_pathbuilder.wisski_pathbuilder.*:
  type: config_entity
  label: 'Pathbuilder'
  mapping:
    id:
      type: string
      label: 'Pathbuilder ID'
    name:
      type: label
      label: 'Label'
    adapter:
      type: string
      label: 'The adapter this pathbuilder belongs to.'
    type:
      type: string
      label: 'The type of this pathbuilder.'
    pathtree:
      type: sequence
      'label': 'Store an array of paths as duo (ID, children)'
      sequence:
        type: mapping
        mapping:
          key: 
            type: string
            label: the key
          value:
            type: string
            label: the value
    pbpaths:
      type: sequence
      'label': 'Store an array of paths as ten-tupel (ID, weight, enabled, parent, bundle, field, fieldtype, displaywidget, formatterwidget, relativepath)'
      sequence:
        type: mapping
        mapping:
          key: 
            type: string
            label: the key
          value:
            type: string
            label: the value

wisski_pathbuilder.wisski_path.*:
  type: config_entity
  label: 'Path'
  mapping:
    id:
      type: string
      label: 'Path ID'
    name:
      type: label
      label: 'Label'
    uuid:
      type: string
      label: 'uuid'
    path_array:
      type: sequence
      'label': 'Store an array of concept-property pairs as path' 
      sequence:
        type: mapping
        mapping:
          key:
            type: string
            label: the key
          value:
            type: string
            label: the value
    datatype_property:
      type: string
      label: 'Datatype Property'
    short_name:
      type: string
      label: 'Short Name'
    disamb:
      type: integer
      label: 'Disambiguation'
    length:
      type: integer
      label: 'Length'
    description:
      type: string
      label: 'Description'
    type:
      type: string
      label: 'Type of the Path'
