<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
/** Module wisski_authfile
 *
 * @author: Martin Scholz
 */
/**
 * Implements hook_help().
 */
function wisski_authfile_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.wisski_authfile':
      return '<p>' . t('This is the WissKI module for authority file integration') . '</p>';
  }
}


/**
 * Implementation of hook_ENTITY_TYPE_presave
 * for WissKI's entity type
 */
# By Mark: This results in double triplification - why should we want to do
# that?!
#function wisski_authfile_wisski_individual_presave(Drupal\Core\Entity\EntityInterface $entity) {
#  wisski_authfile_complete_authority_entry($entity);
#}


/**
 * Implementation of hook_ENTITY_TYPE_insert
 * for WissKI's entity type
 */
function wisski_authfile_wisski_individual_insert(EntityInterface $entity) {
    wisski_authfile_update_authority_uri($entity);
}


/**
 * Implementation of hook_ENTITY_TYPE_update
 * for WissKI's entity type
 */
function wisski_authfile_wisski_individual_update(EntityInterface $entity) {
    wisski_authfile_update_authority_uri($entity);
}

/*
function wisski_authfile_entity_prepare_view($entity_type_id, array $entities, array $displays, $view_mode) {
#  dpm($entity_type_id, "enttype");

  if($entity_type_id == "wisski_individual") {
    foreach($entities as $entity) {
#      dpm(serialize($entity->id()), "ent");
      wisski_authfile_complete_authority_entry($entity);
      wisski_authfile_update_authority_uri($entity);

    }
  }
}
*/

function wisski_authfile_wisski_individual_load($entities) {
  foreach($entities as $entity) {
#    dpm("yay?");
#    dpm($entity, "ente?");
    wisski_authfile_complete_authority_entry($entity);
    wisski_authfile_update_authority_uri($entity);
  }
}

function wisski_authfile_complete_authority_entry($entity) {
#  $actions = entity_load_multiple_by_properties('action', array('plugin' => 'wisski_authfile_complete_info'));
  $actions = \Drupal::entityTypeManager()->getStorage('action')->loadByProperties(array('plugin' => 'wisski_authfile_complete_info'));
#dpm(count($actions), 'actions ci');  
  foreach ($actions as $action) {
    $action->execute([$entity]);
  }
}


function wisski_authfile_update_authority_uri($entity) {
#  $actions = entity_load_multiple_by_properties('action', array('plugin' => 'wisski_authfile_update_uri'));
  $actions = \Drupal::entityTypeManager()->getStorage('action')->loadByProperties(array('plugin' => 'wisski_authfile_update_uri'));
#dpm(count($actions), 'actions ui');  

  foreach ($actions as $action) {
    $action->execute([$entity]);
  }
}
