<?php

use Drupal\Core\Routing\RouteMatchInterface;
/**
 * Implements hook_help().
 */
function wisski_editlayout_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.wisski_editlayout':
      return '<p>' . t('This is the WissKI module for a better layout ' .
      'in forms.') . '</p>';
  }
}


function wisski_editlayout_form_wisski_individual_form_alter (&$form) {
  
  $form['#attached']['library'][] = 'wisski_editlayout/std';

}
