<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\wisski_pathbuilder\Entity\WisskiPathbuilderEntity;
use Drupal\wisski_salz\Entity\Adapter;
/**
 * Implementation of Hook_help
 */
function wisski_adapter_skos_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.wisski_adapter_skos':
      return '<p>' . t('This is the adapter for handling skos based on the sparql adapter.') . '</p>';
  }
}

function wisski_adapter_skos_wisski_individual_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
#  drupal_set_message("smthg: " . serialize($entity));
#  dpm($build);
#  $feld = $build['#wisski_individual']->fb4a22e00d8b6ed5d8a01cf297195355; #->0['#context']['value'] = "Hans Kaspar!";
#  dpm($feld->getValue());
#  $build['#wisski_individual']->fb4a22e00d8b6ed5d8a01cf297195355->setValue("Hans kaspar");
#  
#  dpm($build['#wisski_individual']->fb4a22e00d8b6ed5d8a01cf297195355->getValue());
#
#  dpm($build);

}

function wisski_adapter_skos_field_widget_form_alter(&$element, FormStateInterface $form_state, $context) {
#  drupal_set_message("fun: " . serialize(func_get_args()));
  $field_for_this = $context['items']->getFieldDefinition()->getName();
#  drupal_set_message("I am evil!!!" . serialize($context['items']->getFieldDefinition()->getName()));
#drupal_set_message("I am evil!!!" . serialize($form_state));
#drupal_set_message("I am evil!!!" . serialize($context['widget']));
  
  $pbs = WisskiPathbuilderEntity::loadMultiple();
  
  foreach($pbs as $pb) {
    // if we have no adapter for this pb it may go home.
    if(empty($pb->getAdapterId()))
      continue;
      
    $adapter = Adapter::load($pb->getAdapterId());

    // if we have not adapter, we may go home, too
    if(empty($adapter))
      continue;
    
#    // if he didn't ask for us...    
#    if($this->getConfiguration()['id'] != $adapter->getEngine()->getConfiguration()['id'])
#      continue;
  
    $pbarray = $pb->getPbEntriesForFid($field_for_this);
    
    if(empty($pbarray["id"]))
      continue;
      
#    drupal_set_message(serialize($element));
    
    $element["value"]['#autocomplete_route_name'] = 'wisski_adapter_sparql11_pb.wisski_autocomplete';
    $element["value"]['#autocomplete_route_parameters'] = array("fieldid" => $field_for_this, "pathid" => $pbarray["id"], "pbid" => $pb->id(), "engineid" => $adapter->id());
#    dpm($element);
#    $element["value"]['#attributes']['class'][] = 'aaaaaaaaaaaaaaargh';

#    $element->processAutocomplete($element, $form_state, $context);

#    drupal_set_message(serialize($element));

    break;
  
  }
}



